### ISSUE TITLE
No Documentation On fGUI

### ISSUE THREAD

**Issue by supercoolgamer35** [designer1337/csgo-cheat-base#1]
Sorry if this seems like a lack luster post but can anyone help me with fGui. I simply tried to move the checkbox over to Miscellaneous and its now only rendering the miscellaneous tab.

#include "fgui_menu.hpp"

void gui::initialize() {
    fgui::element_font title_font = { "Tahoma", 11, fgui::external::font_flags::SHADOW , false };
    REGISTER_NOTIFICATIONS(title_font);
    ADD_WINDOW(vars::container["#window"], 50, 50, "csgo-cheat", 560, 450, fgui::external::key_code::KEY_INSERT, title_font);
    REGISTER_CURSOR(fgui::cursor_type::ARROW, fgui::input_state::UNLOCKED);

    REGISTER_TAB(vars::tabs["#tab_panel"], 7, 1, title_font, vars::container["#window"], -1);

    ADD_TAB(vars::tabs["#tab_panel"], "Aimbot"); {
    }

    ADD_TAB(vars::tabs["#tab_panel"], "visuals"); {
    }

    ADD_TAB(vars::tabs["#tab_panel"], "Misc"); {
        ADD_GROUPBOX(vars::container["#groupbox"], 15, 40, "Cool Box NGL", 260, 370, title_font, vars::container["#window"], 0, false, false, false);
        ADD_CONTROLLER(vars::container["#groupbox"], vars::tabs["#tab_panel"]);
        ADD_CHECKBOX(vars::checkbox["#checkbox"], 15, 15, "checkbox gang", "vars.checkbox", title_font, vars::container["#groupbox"], 0);

        ADD_GROUPBOX(vars::container["#groupbox1"], 285, 40, "Cool Box NGL 2", 260, 370, title_font, vars::container["#window"], 0, false, false, false);
        ADD_CONTROLLER(vars::container["#groupbox1"], vars::tabs["#tab_panel"]);
    }
}

**Comment by k1ngboo** [comment]
also something in the code fucked up the github markdown sorry ^

**Comment by 1337Nexo** [comment]
If there's nothing in these tabs, why render them?

lmao..

**Comment by bruhmoment21** [comment]
make sure you put the relevant number at page

**Comment by supercoolgamer35** [comment]
> make sure you put the relevant number at page

You just bumped a 5 month old thread lmao

**Comment by TRMNL** [comment]
bumped a 3 yearold thread L
