### ISSUE TITLE
hooking drawmodel for chams

### ISSUE THREAD

**Issue by milkshakegirlcollector** [designer1337/csgo-cheat-base#101]
Not quite sure how to go about this, Hopefully someone who has a brain can help me here 😅

**Comment by ghost** [comment]
what is your issue, im confused

**Comment by milkshakegirlcollector** [comment]
> what is your issue, im confused

I am not sure how to go about doing chams. I am pretty sure i have to hook something but I do not have brain to do it.

**Comment by ghost** [comment]
hook endscene or something? i still dont understand your issue

**Comment by milkshakegirlcollector** [comment]
> hook endscene or something? i still dont understand your issue

I need to hook DrawModelExecute to draw chams from what I have seen. I don't know why you are trying to tell me to hook endscene when that is clearly done for you in the cheat base.

**Comment by johannes-ll** [comment]
do it like in this source: https://github.com/ChoZenTime/csgo-cheat-pasted-by-choZen/blob/master/core/hooks/hooks.cpp

**Comment by milkshakegirlcollector** [comment]
> do it like in this source: https://github.com/ChoZenTime/csgo-cheat-pasted-by-choZen/blob/master/core/hooks/hooks.cpp

thanks but ended up figuring it out myself. Shout out to Dave, my homie!!

**Comment by SKTen** [comment]
> > 像這個來源：https://github.com/ChoZenTime/csgo-cheat-pasted-by-choZen/blob/master/core/hooks/hooks.cpp
> 
> 謝謝，但最終我自己弄清楚了。向戴夫大聲喊叫，我的朋友！

How to do?
