### ISSUE TITLE
Keybind in the GUI but how?

### ISSUE THREAD

**Issue by papstuc** [designer1337/csgo-cheat-base#102]
How would you add a Keybind input into the CheatMenu like which key the third person should be bound on?

**Comment by milkshakegirlcollector** [comment]
I am pretty sure it is just FGUI, so look at that.

**Comment by ghost** [comment]
wrong, it's not FGUI.

anyways its piss easy, draw a square, detect key presses and store it

the way i do it is i have my own function for detecting input, for keys, text, etc

**Comment by papstuc** [comment]
thanks helped me.

**Comment by ghost** [comment]
why didn't you think of that in the first place? im confused.

**Comment by papstuc** [comment]
well idk

**Comment by ghost** [comment]
how are u gonna be a programmer when something so trivial is difficult to brainstorm?

**Comment by papstuc** [comment]
I just didnt think about it probably.

**Comment by ghost** [comment]
so instead of thinking abt it for more than 3 seconds you create a github issue? ok lol

**Comment by espero-dev** [comment]
what is the keybind?
