### ISSUE TITLE
Type Text

### ISSUE THREAD

**Issue by HackerGeo-sp1ne** [designer1337/csgo-cheat-base#19]
How to add a type text to framework menu?

**Comment by designer1337** [comment]
render::draw_text_string();

**Comment by HackerGeo-sp1ne** [comment]
not this, for example to clan tag, to type custom tag

**Comment by HackerGeo-sp1ne** [comment]
and add button please, if you added this is completed base
Thank you! you have discord?

**Comment by HackerGeo-sp1ne** [comment]
and add button please, if you added this is completed base
Thank you! you have discord?
