### ISSUE TITLE
Material loading

### ISSUE THREAD

**Issue by BuddDwyer-0x00** [designer1337/csgo-cheat-base#23]
You'd need the hook for "CheckFileCRCsWithServer"
https://www.unknowncheats.me/forum/counterstrike-global-offensive/392489-fixing-sv_pure-kicks.html

But i'm not too familiar with this source and the hooking looks weird, would be good if someone better would update it.

**Comment by designer1337** [comment]
Or just don't create materials with shitty ostream way, use proper keyvalues material creation.

**Comment by BuddDwyer-0x00** [comment]
fair enough, i made the hook, should i add it here?
