### ISSUE TITLE
request to contribute

### ISSUE THREAD

**Issue by michael7845** [designer1337/csgo-cheat-base#30]
are there any requirements for contributions and could I have an invite?

**Comment by BuddDwyer-0x00** [comment]
Just upload ur changes, designer can either accept or reject.

**Comment by michael7845** [comment]
I can't make a pull request unless I have my own branch apparently and I need to be a contributor for that (is what I read online.)

**Comment by designer1337** [comment]
> I can't make a pull request unless I have my own branch apparently and I need to be a contributor for that (is what I read online.)

Create a fork.
