### ISSUE TITLE
How am I supposed to use interfaces::entity_list->get_client_entity()

### ISSUE THREAD

**Issue by DualByte** [designer1337/csgo-cheat-base#37]
When I give it a index like this:
`for (size_t i = 1; i < 64; i++) {
interfaces::entity_list->get_client_entity(i); //How am I supposed to get something out of this?
}`
I cant get anything from that function.

**Comment by designer1337** [comment]
`
auto entity = interfaces::entity_list->get_client_entity(i);

entity->health();
`

**Comment by DualByte** [comment]
Oh thank you. Im just retarded

**Comment by DualByte** [comment]
There is still a one problem. When I do
`auto entity = interfaces::entity_list->get_client_entity(i);`
`entity->health();`
It gives me a error that says "expression must have pointer-to-class type"

**Comment by designer1337** [comment]
```
		auto entity = reinterpret_cast<player_t*>(interfaces::entity_list->get_client_entity(i));
```

**Comment by DualByte** [comment]
Thank you!
