### ISSUE TITLE
no an issue - text size

### ISSUE THREAD

**Issue by realstyla23** [designer1337/csgo-cheat-base#39]
really love the base.. thx for sharing.. learned a loot again.. but can you tell me where to change the font and textsize of menu etc..

**Comment by designer1337** [comment]
https://github.com/designer1337/csgo-cheat-base/blob/5b72b65733edc0834831e200cfacfbcbc695a617/dependencies/utilities/renderer/renderer.cpp#L6

**Comment by designer1337** [comment]
interfaces::surface->set_font_glyph(render::fonts::watermark_font, "Tahoma", 12, 500, 0, 0, font_flags::fontflag_dropshadow);

**Comment by realstyla23** [comment]
yea i just found it :D before u wrote it haha.. but thx!
