### ISSUE TITLE
Text appearing twice after using render::draw_text_string and render::draw_text_wchar

### ISSUE THREAD

**Issue by DualByte** [designer1337/csgo-cheat-base#45]
If you place the text as an example to a players head's location the text is visible on the players head where it is supposed be but when you rotate 180 degrees you can see the text just levitating.

**Comment by designer1337** [comment]
Thats not issue, most likely ur missing dormant checks

**Comment by DualByte** [comment]
There are dormant checks and it is literally drawing it exactly 180 degrees from the position where it is supposed to be.

**Comment by designer1337** [comment]
that's problem related to your code, most likely dormant fade or something, it's working completely fine for me.


also, I can't help u without any code provided
