### ISSUE TITLE
Crash when detaching while in debug

### ISSUE THREAD

**Issue by mrxrk** [designer1337/csgo-cheat-base#56]
hey, does this crash only occurs for me? When I compiled the base in debug and pressing END the game crashes - doesn't happen in release build. So probably something with the console? 
Debug log is : "A LIST_ENTRY has been corrupted (i.e. double remove)."

**Comment by bruhmoment21** [comment]
seems to work for me

**Comment by mrxrk** [comment]
Already attached a debugger, also happen in release build with that setup. How can I debug that better?
Always on FreeLibraryAndExitThread

**Comment by bruhmoment21** [comment]
can you show your whole main.cpp file?

**Comment by mrxrk** [comment]
think I fixxed it, the problem wasn't in the code from the cheat, it was in my injector. I unlinked the PEB, that's why I couldn't detach it. Seems like I fixed it, thanks for your fast help tho!
