### ISSUE TITLE
insecure injection is crashing since last upd

### ISSUE THREAD

**Issue by behality** [designer1337/csgo-cheat-base#60]
`globals = **reinterpret_cast< c_global_vars_base *** >( ( *reinterpret_cast< uintptr_t ** >( client )[ 11 ] + 10 ) );`

this line seems crashing, is indexes was updated?

**Comment by designer1337** [comment]
0 + 27

**Comment by jon4dev** [comment]
Idk why but 11 + 10 works fine for me but 0 27 im getting insta crash?

**Comment by behality** [comment]
globals = **reinterpret_cast< c_global_vars_base *** >( ( *reinterpret_cast< uintptr_t ** >( client )[ 0 ] + 0x1F ) );
working fine (tested in insecure mode)
