### ISSUE TITLE
Menu BUG

### ISSUE THREAD

**Issue by jon4dev** [designer1337/csgo-cheat-base#61]
Hello, i noticed when csgo is in windowed mode menu dont work i cant select checkbox/slider etc.

**Comment by bruhmoment21** [comment]
don t use this menu framework if you are beginner. better take a look at zgui and see how the input is handled.. etc

**Comment by ghost** [comment]
Instead of using the WINAPI GetCursorPos use the function in interfaces->inputsystem->getcursorpos.
