### ISSUE TITLE
Cant inject without -insecure

### ISSUE THREAD

**Issue by sowwe** [designer1337/csgo-cheat-base#66]
injector: xenos
error: 0xC0000135 
metods: native, manual map

not sure if this is a cheat bug, but after the update I can't inject without insecure.

**Comment by jon4dev** [comment]
Because u injector dont bypass the new anti-cheat?

**Comment by sowwe** [comment]
> Because u injector dont bypass the new anti-cheat?

maybe, can u recommend working injector, please?

**Comment by jon4dev** [comment]
https://www.cshacked.pl/csh-injector-09072020-t156933/
https://www.cshacked.pl/embbypass-11072020-t157042/
https://github.com/martinjanas/RandoInjector

**Comment by sowwe** [comment]
Thanks!
