### ISSUE TITLE
sv_cheats help

### ISSUE THREAD

**Issue by bruhmoment21** [designer1337/csgo-cheat-base#7]
i am trying to hook sv_cheats like this
```
// .hpp file
namespace sv_cheats {
		using fn = bool( __thiscall* )( convar* );
		static bool __fastcall hook( ) noexcept;
	}

// .cpp file
hooks::sv_cheats::fn sv_cheats_original = nullptr;
auto sv_cheats_target = reinterpret_cast< void* >( get_virtual( interfaces::console->get_convar( "sv_cheats" ), 13 ) );

if ( MH_CreateHook( sv_cheats_target, &sv_cheats::hook, reinterpret_cast< void** >( &sv_cheats_original ) ) != MH_OK ) {
		throw std::runtime_error( "failed to initialize sv_cheats. (outdated index?)" );
		return false;
	}

static bool __fastcall hooks::sv_cheats::hook( ) noexcept {
	if ( interfaces::engine->is_in_game( ) && config_system.esp.thirdperson ) {
		static auto think = utilities::pattern_scan( GetModuleHandleA( "client_panorama.dll" ), "85 C0 75 30 38 86" );
		static auto original_fn = sv_cheats_original( interfaces::console->get_convar( "sv_cheats" ) );
		if ( !original_fn )
			return false;

		if ( reinterpret_cast< DWORD >( _ReturnAddress( ) ) == reinterpret_cast< DWORD >( think ) )
			return true;
		return original_fn;
	}
}
```
![image](https://user-images.githubusercontent.com/53657322/79694360-8064d680-8278-11ea-8828-88a31950b853.png)
this is what i get for hooking it. i appreciate any help!

**Comment by designer1337** [comment]
`

bool __fastcall hooks::sv_cheats_get_bool::hook(PVOID convar, int edx) {
	if (!convar)
		return false;

	if ((_ReturnAddress()) == cam_think && csgo::local_player && csgo::local_player->is_alive())
		return true;
	else
		return sv_cheats_get_bool_original(convar);
}



`

**Comment by designer1337** [comment]
No need to cast sig and return address to DWORD...

**Comment by bruhmoment21** [comment]
still have it. didn't fix

**Comment by designer1337** [comment]
works fine for me using method above

**Comment by bruhmoment21** [comment]
lol it worked the whole time. with alphauc hooking method you could use commands that needed sv_cheats like r_drawothermodels with this hooking method you can't use them
