### ISSUE TITLE
Third person anti-aim not showing even when setting local view angles.

### ISSUE THREAD

**Issue by AhamYT** [designer1337/csgo-cheat-base#9]
So in this base, there are no set local view angles(in prediction). So I went to UC and found the netvar dead flag and 4 past it, you can set local view angles. So I do this in FRAME_RENDER_START, and It still doesn't work. I think this is a base issue. Because in alphas SDK you can use deadflag+4 fine [https://github.com/alphauc/sdk](url) and an example of this being done is from polandhack [https://github.com/alphauc/polandhack/blob/master/src/cheat/hooks/client_dll/frame_stage_notify.cc](url) here is my code for FRAME_RENDER_START
`if (frame_stage == FRAME_RENDER_START)
	{
		if (csgo::local_player && csgo::local_player->is_alive())
		{
			if (vars::checkbox["#enableThirdperson"]->get_bool())
			{
				interfaces::input->m_fCameraInThirdPerson = true;
				*(vec3_t*)((uintptr_t)csgo::local_player + 0x31C8) = vec3_t(real.x, real.y, 0);
			}`

**Comment by designer1337** [comment]
```
void set_local_view_angles(vec3_t& angles) {
		using original_fn = void(__thiscall*)(void*, vec3_t&);
		return (*(original_fn**)this)[13](this, angles);
	}
```

**Comment by designer1337** [comment]
Also 0x31C8 is probably outdated.
