### ISSUE TITLE
Gradient Line?

### ISSUE THREAD

**Issue by bloomsaccount** [designer1337/csgo-cheat-base#91]
How I would I render a 3 way gradient line?

**Comment by noor0x07** [comment]
take 3 colors, make a function with basic math to make it into a gradient, idk whats hard about this and i found what you need in 14 seconds of duckduckgo'ing

stay cool, sent from dora the explorer toy phone with camera

**Comment by iLostMyXbox21** [comment]
https://bfy.tw/PfPe
